### PR TITLE
[BitSail-433][Core] Support Timestamp type in RowUtil

### LINKED ISSUE #433: [Bug][Core] Not support Timestamp type in RowUtil
### What happened

When I run a reader job in which source data has `date` type, there are logs:

```
InputAdapter -> Sink: print-sink (2/2)] INFO  c.b.bitsail.flink.core.util.RowUtil - Object value = 2023-03-06 18:55:04.618 can't supported in current.
```

### What do you expect to happen

`Timestamp` is a basic type, and should be supported correctly.

### How to reproduce

Run a reader job in which source data has `date` type.

### Build Environment

_No response_

### Execution Environment

_No response_

### BitSail version

master

### BitSail Component or Code Module

BitSail Core

### Are you willing to submit PR?

- [X] Yes, I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/bytedance/bitsail/blob/master/CODE_OF_CONDUCT.md)

### PR DESCRIPTION
**Pull request by healchow**
## Pre-Checklist

- [x] I have read through the [CONTRIBUTING.md](https://github.com/bytedance/bitsail/blob/master/docs/contributing.md) documentation.
- [x] My code has the necessary comments and documentation (if needed).
- [x] I have added relevant tests.

## Purpose

Support Timestamp type in RowUtil.

## Approaches

Change the import class from `java.secure.Timestamp` to `java.sql.Timestamp`.

## Related Issues

- Fixes #433

### CODE REVIEW

File: bitsail-cores/bitsail-core-flink-base/src/main/java/com/bytedance/bitsail/flink/core/util/RowUtil.java [hunk 1]
```diff
@@ -139,7 +139,7 @@ private static long getNormalTypeByteSize(Object field) {
       return 15L;
     }
 
-    LOG.debug("Object value = {} can't supported in current.", field);
+    LOG.debug("Unsupported type [{}] for object value [{}]", clazz.getName(), field);
```
Comment (healchow) [inline bitsail-cores/bitsail-core-flink-base/src/main/java/com/bytedance/bitsail/flink/core/util/RowUtil.java:142]: The log format like this:
```
Unsupported type [java.sql.Timestamp] for object value [2023-03-06 18:55:04.618]
```

**Comment by healchow** [comment]
> @healchow CI/CD failed, can you take a look?

Hello, I saw from the workflow log that a JVM crash occurred when running unit tests in `FlinkRunnerSavepointLoaderTest`, but I didn't see the use of `System.exit` in this test class.

From other information, I think this may be caused by OOM, for more information:

[forked-vm-terminated](https://stackoverflow.com/questions/23260057/the-forked-vm-terminated-without-saying-properly-goodbye-vm-crash-or-system-exi)

I'll try again by retriggering the workflow.
If the problem exists, then I will try to set the JVM heap size to solve it.
